### PR TITLE
Switch remote pull to docker.errors.NotFound

### LINKED ISSUE #20: Crash when image doesn't exist on Dockerhub
When attempting to use an image that does not exist on Dockerhub but exists locally, a chain of exceptions is raised which results in the process crashing.

Expected behavior: chainlink gracefully handles the lack of an image on Dockerhub and falls back to the local image.

<details>
<summary>Relevant Logs:</summary>

```
INFO:root:Starting job 5d0560b9c3e0992fd5ef770b
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/jason/Documents/broadway-grader/env/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/create?tag=0.2.1&fromImage=jasonbilas%2Fquartus_build

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jason/Documents/chainlink/chainlink/__init__.py", line 69, in _pull_image
    client.images.pull(image)
  File "/home/jason/Documents/broadway-grader/env/lib/python3.7/site-packages/docker/models/images.py", line 441, in pull
    repository, tag=tag, stream=True, **kwargs
  File "/home/jason/Documents/broadway-grader/env/lib/python3.7/site-packages/docker/api/image.py", line 400, in pull
    self._raise_for_status(response)
  File "/home/jason/Documents/broadway-grader/env/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/jason/Documents/broadway-grader/env/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("manifest for jasonbilas/quartus_build:0.2.1 not found: manifest unknown: manifest unknown")

--- Logging error ---
Traceback (most recent call last):
  File "run.py", line 95, in worker_routine
    chain = Chainlink(job[api_keys.STAGES], workdir=os.getcwd())
  File "/home/jason/Documents/chainlink/chainlink/__init__.py", line 27, in __init__
    self._pull_images()
  File "/home/jason/Documents/chainlink/chainlink/__init__.py", line 64, in _pull_images
    raise ValueError("Failed to pull all images")
ValueError: Failed to pull all images

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "run.py", line 98, in worker_routine
    logger.critical("Grading job failed with exception:\n{}", ex)
Message: 'Grading job failed with exception:\n{}'
Arguments: (ValueError('Failed to pull all images'),)
--- Logging error ---
Traceback (most recent call last):
  File "run.py", line 95, in worker_routine
    chain = Chainlink(job[api_keys.STAGES], workdir=os.getcwd())
  File "/home/jason/Documents/chainlink/chainlink/__init__.py", line 27, in __init__
    self._pull_images()
  File "/home/jason/Documents/chainlink/chainlink/__init__.py", line 64, in _pull_images
    raise ValueError("Failed to pull all images")
ValueError: Failed to pull all images

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "run.py", line 98, in worker_routine
    logger.critical("Grading job failed with exception:\n{}", ex)
Message: 'Grading job failed with exception:\n{}'
Arguments: (ValueError('Failed to pull all images'),)
INFO:root:Finished job 5d0560b9c3e0992fd5ef770b
INFO:root:Job stdout:
The container crashed
INFO:root:Job stderr:
Failed to pull all images
INFO:root:Sending job results
```

</details>

Steps to reproduce:
1. Create docker image locally but don't upload it to dockerhub
2. Create a job that uses the local image using broadway-api
3. Attempt to run that job
4. Witness crash

### PR DESCRIPTION
**Pull request by jasonB221**
This fixes #20 by catching the correct exception.

### CODE REVIEW

**Comment by ayushr2** [comment]
According to the [docs](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.pull) Docker Pull can return `docker.errors.APIError`.

Browsing through the docs it looks like `APIError` is the base error. `NotFound` inherits `APIError` and `ImageNotFound` inherits from `NotFound`. So it looks like the issue was that we were catching the exception from the wrong part in the inheritance chain. It would be best to catch `APIError` here (following the docs)

**Comment by ayushr2** [comment]
Also while you are at it, It looks like we are not completely handling `docker.image.get` exceptions. [Docs](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.get) say that it can throw `docker.errors.ImageNotFound` and `docker.errors.APIError` but we only handle `ImageNotFound`. We should add another `except` statement for `APIError`.

**Comment by nmagerko** [comment]
@ayushr2 the error was too specific, but I see no reason to catch `APIError` here as well. If there's an `APIError` then we're probably not going to be able to do anything useful (except for more logging, which is not the point of this PR).

**Comment by ayushr2** [comment]
Alright, I will incorporate this in another PR.

**Pull request merged**
